#!/usr/bin/env bash

# match window title and class
id=$(wmctrl -lx|grep "${1}"|awk '{ print $1 }')

# stop execution if theres no matches
if [ -z "$id" ] && ! [ -z "$2" ]; then
    ${2}
    exit
fi

id=$(bspc query -N -n .floating)

focusedid=$(bspc query -N -n .focused)

if [ "$id" != "$focusedid" ];then
    bspc node $(cat <<< "$id"|head -n 1) --flag hidden=off --to-monitor focused --focus
else
    bspc node --flag hidden=on
fi
