font-family = "FiraCode Nerd Font Mono Med"
font-family-bold = "FiraCode Nerd Font Mono Bold"
font-family-bold-italic = "FiraCode Nerd Font Mono Bold"
font-family-italic = "FiraCode Nerd Font Mono Light"
font-feature = "+ss02"

gtk-single-instance = true
theme = "GruvboxDark"

keybind = "clear"
keybind = "ctrl+shift+v=paste_from_clipboard"
keybind = "ctrl+shift+c=copy_to_clipboard"
keybind = "ctrl+down=decrease_font_size:1"
keybind = "ctrl+up=increase_font_size:1"
keybind = "ctrl+equal=reset_font_size"
