ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0
enableAllRules = true

[rule.add-constant]
Disabled = true
[rule.exported]
Disabled = true
[rule.package-comments]
Disabled = true
[rule.banned-characters]
Disabled = true
[rule.max-public-structs]
Disabled = true
[rule.file-header]
Disabled = true
[rule.function-length]
Disabled = true

[rule.line-length-limit]
Arguments = [120]
[rule.argument-limit]
Arguments = [5]
[rule.cyclomatic]
Arguments = [10]
[rule.cognitive-complexity]
Arguments = [7]
[rule.function-result-limit]
Arguments = [3]
