#!/usr/bin/env bash

set -e

if test -e /dev/tty; then
	luajit </dev/tty ~/.config/git/hooks/test-secrets.lua
else
	luajit ~/.config/git/hooks/test-secrets.lua
fi

prek hook-impl --hook-type pre-commit --skip-on-missing-config --
