# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bd02f4bd-b67a-4a42-9fc4-2ac464263168";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8C2D-CEDA";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3576143b-55b0-41ce-af04-a9eeefba0c3f"; }
    ];

  boot.initrd = {
    secrets = {
      "/crypto_keyfile.bin" = null;
    };
    luks.devices = {
      "luks-6b11644b-f8ea-4158-90e2-278224ebf5d7" = {
        device = "/dev/disk/by-uuid/6b11644b-f8ea-4158-90e2-278224ebf5d7";
      };
      "luks-61a8f812-0b86-4be9-9b69-9472960c08b8" = {
        keyFile = "/crypto_keyfile.bin";
        device = "/dev/disk/by-uuid/61a8f812-0b86-4be9-9b69-9472960c08b8";
      };
    };
  };

  boot.loader = {
    efi = {
      efiSysMountPoint = "/boot";
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.ipu6 = {
    enable = true;
    platform = "ipu6ep";
  };
}
