[metadata]
name = "just-recipes"
description = "A channel to select recipes from Justfiles"
requirements = [ "just",]

[source]
command = [ "just --summary | tr '[:blank:]' '\n'",]
output = "just {}"

[preview]
command = "just -s {}"

[keybindings]
ctrl-r = "actions:run"

[actions.run]
description = "Run a justfile recipe"
command = "just {}"
mode = "execute"
