require('gruvbox-material').setup()

vim.api.nvim_set_hl(0, 'CursorLineNr', { ctermfg = 208, bold = true, fg = "#e78a4e" })
vim.api.nvim_set_hl(0, '@markup.heading.1', { link = "markdownH1", default = true })
vim.api.nvim_set_hl(0, '@markup.heading.2', { link = "markdownH2", default = true })
vim.api.nvim_set_hl(0, '@markup.heading.3', { link = "markdownH3", default = true })
vim.api.nvim_set_hl(0, '@markup.heading.4', { link = "markdownH4", default = true })
vim.api.nvim_set_hl(0, '@markup.heading.5', { link = "markdownH5", default = true })
vim.api.nvim_set_hl(0, '@markup.heading.6', { link = "markdownH6", default = true })
vim.api.nvim_set_hl(0, '@markup.link', { link = "Underlined", default = true })
vim.api.nvim_set_hl(0, '@markup.list', { link = "Todo", default = true })
vim.api.nvim_set_hl(0, '@markup.quote', { link = "jsonQuote", default = true })
vim.api.nvim_set_hl(0, '@markup.raw.inline', { link = "IndentRainbowViolet", default = true })
vim.api.nvim_set_hl(0, '@markup.bold', { link = "markdownBold", default = true })
vim.api.nvim_set_hl(0, '@markup.italic', { link = "markdownItalic", default = true })
