require('notify').setup({
  render = "compact",
})
vim.api.nvim_set_hl(0, 'NotifyERRORBorder', { link = "DiagnosticError",    nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyERRORIcon',   { link = "DiagnosticError",    nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyERRORTitle',  { link = "DiagnosticError",    nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyWARNBorder',  { link = "DiagnosticWarn", nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyWARNIcon',    { link = "DiagnosticWarn", nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyWARNTitle',   { link = "DiagnosticWarn", nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyINFOBorder',  { link = "DiagnosticInfo",  nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyINFOIcon',    { link = "DiagnosticInfo",  nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyINFOTitle',   { link = "DiagnosticInfo",  nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBorder', { link = "DiagnosticHint",   nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon',   { link = "DiagnosticHint",   nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle',  { link = "DiagnosticHint",   nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyTRACEBorder', { link = "DiagnosticOk",   nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyTRACEIcon',   { link = "DiagnosticOk",   nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyTRACETitle',  { link = "DiagnosticOk",   nocombine = true })
