require("pi").setup({
  binary = {
    "docker",
    "run",
    "--rm",
    "-i",
    "-e",
    "OPENROUTER_API_KEY",
    "-e",
    "BRAVE_API_KEY",
    "-v",
    "/home/f4z3r/.pi:/home/f4z3r/.pi", -- Write permissions needed for lock files.
    "-v",
    "/home/f4z3r/notes/resources/ai/:/home/f4z3r/notes/resources/ai:ro",
    "-v",
    vim.fn.getcwd() .. ":/home/f4z3r/workspace",
    "ghcr.io/f4z3r/pi-agent-image:v0.2.1",
    "pi",
  },
  provider = "openrouter",
  model = "mistralai/mistral-small-2603",
  max_context_lines = 300,
  max_context_bytes = 24000,
  selection_context_lines = 40,
  log_path = "/tmp/pi-nvim.log",
  skills = true,
  extensions = true,
  tools = true,
})
