#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

music_dir="$HOME/Music"
previewdir="$HOME/.config/ncmpcpp/previews"
filename="$(mpc --format "$music_dir"/%file% current)"
previewname="$previewdir/$(mpc --format %file% current | base64).png"

[ -e "$previewname" ] || ffmpeg -y -i "$filename" -an -vf crop=in_w/2:in_h:in_w/4:0,scale=128:128 "$previewname" > /dev/null 2>&1

notify-send -r 27072 "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)" -i "$previewname"
